<a href="https://colab.research.google.com/github/Chhavi0926/DS_45_InternshipDays/blob/main/DAY_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Table of Contents

1.  **Data Loading and Quick Views** (e.g., `pd.read_json`, `df.head()`, `df.info()`)
2.  **DataFrame Structure & Manipulation** (e.g., `pd.DataFrame`, `pd.Series`, `df.rename()`, adding columns)
3.  **Detailed Data Inspection with Pandas** (e.g., `df.describe()`, `df.shape`, `df.columns`, `df.dtypes`)
4.  **Numerical Operations & Transformations** (e.g., salary increment calculations)

# 1.  **Data Loading and Quick Views**
*(e.g., `pd.read_json`, `df.head()`, `df.info()`)*

In [1]:
# csv file import from github
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df
# head -> starting 5 rows
df.head(2)
# head -> 2 rows data
df.head(-3)
# head -> negative number
df

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df["Salary"] = [100,200,300,np.nan,500] # Adjusted to 5 values to match DataFrame length
df.info()

# df.info(verbose =False)   # Verbose --> true means shows detailed information.Or False-->less info.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
 3   Salary   4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 292.0+ bytes

# 2. **DataFrame Structure & Manipulation**
*(e.g., pd.DataFrame, pd.Series, df.rename(), adding columns)*

In [ ]:
# Rename
import numpy as np
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df
df.rename(columns = {"name":"Student_Name","marks":"Salary"},inplace = True)
# Original value of df -> value same
df

  Student_Name  roll no  Salary
0      dheeraj      123      10
1        kunal     1234      20
2     abhishek    12345      30
3      praveen    12356      40
4       anjali  1234567      50

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"

df = pd.read_json(url)
print("1. Initial DataFrame loaded from URL:")
display(df)
print(f"Shape: {df.shape}\n")

df = pd.DataFrame(data = [10,20,30,40,50], columns = ["age"])
print("2. DataFrame created from a list:")
display(df)
print(f"Shape: {df.shape}\n")

df = pd.Series(data = [10,20,30,40,50], name = "age")
print("3. Series created from a list:")
display(df)
print(f"Shape: {df.shape}")

1. Initial DataFrame loaded from URL:

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

Shape: (5, 3)

2. DataFrame created from a list:

   age
0   10
1   20
2   30
3   40
4   50

Shape: (5, 1)

3. Series created from a list:

0    10
1    20
2    30
3    40
4    50
Name: age, dtype: int64

Shape: (5,)

# 3. **Detailed Data Inspection with Pandas**
 *(e.g., df.describe(), df.shape, df.columns, df.dtypes)*

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df.describe(include='all')

In [ ]:
import pandas as pd

data = {
    "Emp_ID" : [101,102,103,104,105,106],
    "Name" :["Amit",'Riya','Raj','Sara','John','Neha'],
    'Department' : ['HR','IT','Finance','IT','HR','Finance'],
    'Salary' : [60000,70000,50000,80000,55000,65000],
    "Experience" : [2,3,5,4,1,3]
}
df = pd.DataFrame(data)
print(df,"\n")
print('------All PANDAS Functions------')
print('Info :')
print(df.info,"\n")
print('Head :')
print(df.head(),"\n")
print('Tail :')
print(df.tail(),"\n")
print('Shape :')
print(df.shape,"\n")
print('Rename :')
print(df.rename(columns={"Name":"Emp_name"},inplace=True))
print('\n')
print('Describe :')
print(df.describe())
print('\n')
print('Describe Numeric :')
print(df.describe(include='number'))
print('\n')
print('Describe All :')
print(df.describe(include='all'))

## Pandas Functions Demonstration

In [ ]:
# Display the full DataFrame
display(df)

   Emp_ID Emp_name Department  Salary  Experience
0     101     Amit         HR   60000           2
1     102     Riya         IT   70000           3
2     103      Raj    Finance   50000           5
3     104     Sara         IT   80000           4
4     105     John         HR   55000           1
5     106     Neha    Finance   65000           3

In [ ]:
display(df.head())

   Emp_ID Emp_name Department  Salary  Experience
0     101     Amit         HR   60000           2
1     102     Riya         IT   70000           3
2     103      Raj    Finance   50000           5
3     104     Sara         IT   80000           4
4     105     John         HR   55000           1

In [ ]:
display(df.tail())

   Emp_ID Emp_name Department  Salary  Experience
1     102     Riya         IT   70000           3
2     103      Raj    Finance   50000           5
3     104     Sara         IT   80000           4
4     105     John         HR   55000           1
5     106     Neha    Finance   65000           3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Emp_name    6 non-null      object
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

In [ ]:
display(df.describe(include='all'))

            Emp_ID Emp_name Department        Salary  Experience
count     6.000000        6          6      6.000000    6.000000
unique         NaN        6          3           NaN         NaN
top            NaN     Amit         HR           NaN         NaN
freq           NaN        1          2           NaN         NaN
mean    103.500000      NaN        NaN  63333.333333    3.000000
std       1.870829      NaN        NaN  10801.234497    1.414214
min     101.000000      NaN        NaN  50000.000000    1.000000
25%     102.250000      NaN        NaN  56250.000000    2.250000
50%     103.500000      NaN        NaN  62500.000000    3.000000
75%     104.750000      NaN        NaN  68750.000000    3.750000
max     106.000000      NaN        NaN  80000.000000    5.000000

In [ ]:
print(df.shape)

(6, 5)

In [ ]:
print(df.columns)

Index(['Emp_ID', 'Emp_name', 'Department', 'Salary', 'Experience'], dtype='object')

### `df.dtypes`: List the data types of each column

In [ ]:
print(df.dtypes)

Emp_ID         int64
Emp_name      object
Department    object
Salary         int64
Experience     int64
dtype: object

In [ ]:
import pandas as pd
import numpy as np # Import numpy
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url) # Load JSON
display(df['name']) # Show 'name' column
df['salary'] = [np.nan] * len(df) # Add 'salary' column
display(df) # Show updated df

0     dheeraj
1       kunal
2    abhishek
3     praveen
4      anjali
Name: name, dtype: object

       name  roll no  marks  salary
0   dheeraj      123     10     NaN
1     kunal     1234     20     NaN
2  abhishek    12345     30     NaN
3   praveen    12356     40     NaN
4    anjali  1234567     50     NaN

# 4. **Numerical Operations & Transformations**
*(e.g., salary increment calculations)*

In [ ]:
import pandas as pd # Import pandas library

d = { # Create dictionary for DataFrame
"name":["vishal","virat","vineet"],
"salary":[100,200,300]
}
df = pd.DataFrame(data=d) # Create DataFrame
df["marks"] = df["salary"] / 2 # Calculate marks
df # Display initial DataFrame

# Increment salary by 10%
print('Original DataFrame')
print(df,'\n\n')
print('DataFrame with incremented salaries')
df['salary'] = df['salary'] * 1.10 # Apply 10% salary increment
df # Display updated DataFrame

Original DataFrame
     name  salary  marks
0  vishal     100   50.0
1   virat     200  100.0
2  vineet     300  150.0


DataFrame with incremented salaries

     name  salary  marks
0  vishal   110.0   50.0
1   virat   220.0  100.0
2  vineet   330.0  150.0